apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline
spec:
  type: NodePort
  selector:
    name: complete-prodcution-e2e-pipeline
  ports:
    - port: 8080
      targetPort: 8080

      nodePort: 30007
